### ISSUE TITLE
PDF files of T1-T6 need to be added for download

### ISSUE THREAD

**Issue by The-Kergan** [zeue/coronavirus-toolkit#24]
**Describe the bug**
The tools we are providing are not available for download.

**Action needed**
All the pdf files saved in \\Dropbox\COVID-19\1-WORK OUTPUT\WEEK 1\FINAL need to be added to the site:

1. Directly under the F1 heading: All 6 PDFs (T1..T6) need to be added as separate downloadable files (minimum) or behind a button saying 'Download all F1 Tools' in a single zip file (ideal)
2. Directly under each T1, T2, T3, Tn heading: Corresponding pdf of the tool - eg T1 heading should have the T1-Coronavirus Symptom Tracker-v4.pdf file to download

**Comment by geoffwasham** [comment]
Links to the PDFs have been provided under each Tool header, and a zipped file has been linked under the F1 header.
