### ISSUE TITLE
Site Branding

### ISSUE THREAD

**Issue by The-Kergan** [zeue/coronavirus-toolkit#25]
**Request**
Would like the site branded

**Describe the solution you'd like**

1. Site to have a logo (\Dropbox\COVID-19\3-BRANDING\logo-toolkit-design-text.png)
2. Headers to reflect the RGB colors of the documents/logo (RGB guide image here - let me know if you don't know how to convert this to html format \Dropbox\COVID-19\3-BRANDING\logo-rgb.jpg)

**Describe alternatives you've considered**
I assume the color pallette can be set fairly easily in CSS?

**Comment by The-Kergan** [comment]
![download-tools-button](https://user-images.githubusercontent.com/44531202/77971622-2d24e700-72bd-11ea-846f-2994bfa617e7.png)
I produced a button to use to 'Download Tools' - uses approved color scheme.

**Comment by The-Kergan** [comment]
![logo-hex-rgb](https://user-images.githubusercontent.com/44531202/77972061-627e0480-72be-11ea-9a69-23652ca4b597.jpg)
Hex color codes for site.

**Comment by The-Kergan** [comment]
Logo in top left corner should replace 'Home' header & link.

![logo-toolkit-design-text](https://user-images.githubusercontent.com/44531202/78038237-9c8cec00-733a-11ea-9f89-fd7ceb2a002a.png)

**Comment by The-Kergan** [comment]
Need Toolkit [Favicon](https://stackoverflow.com/questions/4888377/how-to-add-a-browser-tab-icon-favicon-for-a-website) on browser tabs

![logo-toolkit-design](https://user-images.githubusercontent.com/44531202/78038405-ce9e4e00-733a-11ea-8765-bc4c957a9e58.png)

**Comment by The-Kergan** [comment]
### Proposals for CSS styles
H1: Purple #990066
H2 - Hn: Taupe #219a93

**Comment by zeue** [comment]
done in fb5573d
