### ISSUE TITLE
F3: Keeping us and our delivery drivers safe

### ISSUE THREAD

**Issue by The-Kergan** [zeue/coronavirus-toolkit#29]
**Week 3 Focus**
F3: Keeping us and our delivery drivers safe due 10 April 2020

**Describe the solution you'd like**
Add F3 to the left tool bar as a placeholder. Also need to add F2 as a placeholder too. We will add new tools under each as they are developed.

Eg
F2: Living in a household with someone with coronavirus symptoms (due 3 April 2020)
F3: Keeping us and our delivery drivers safe (due 10 April 2020)

**Comment by geoffwasham** [comment]
Placeholders added.
